/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package phoenixbuilder */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h> /* for ptrdiff_t below */

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 18 "bridge.go"

static void** cbs=NULL;
static inline void SetCallbackSheet(void *cbs1) {
	cbs=cbs1;
}
static inline void ReportPanic(char *error) {
	((void(*)(char*))cbs[0])(error);
}
static inline void LoginFailed(char *msg) {
	((void(*)(char*))cbs[1])(msg);
}
static inline void InitFinished() {
	((void(*)(void))cbs[2])();
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef __SIZE_TYPE__ GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern char* loadToken();
extern char* generateTempToken(GoString username, GoString password);
extern GoUint8 hasToken();
extern void setCallbacks(void* cbs);
extern void runLibClient(char* _guiversion, char* _token, char* _serverCode, char* _serverPassword);
extern GoString GetFBVersion();
extern GoUint8 isDebugMode();
extern void removeToken();
extern void _executeFastBuilderCommand(char* cmd);
extern void _executeMinecraftCommand(char* cmd);
extern void _sendChat(char* content);
extern char* _getBuildPos();
extern char* _getEndPos();
extern void teardownFastBuilder();

#ifdef __cplusplus
}
#endif
